Collision mapcheck
TheEmidee/UEMapCheckValidation pull request #15
Opened 2023-02-01 11:42 UTC by VectorGamez

2023-02-01 13:52 UTC, TheEmidee requested changes

2023-02-01 13:52 UTC, TheEmidee commented on Source/Private/Validators/MapCheckValidator_Collisions.cpp
> +#include "Misc/UObjectToken.h"
<>

2023-02-01 13:52 UTC, TheEmidee commented on Source/Private/Validators/MapCheckValidator_Collisions.cpp
> +#include <Engine/Light.h>
is this needed?

2023-02-01 14:08 UTC, VectorGamez commented on Source/Private/Validators/MapCheckValidator_Collisions.cpp
> +#include <Engine/Light.h>
Removed.

2023-02-01 14:08 UTC, VectorGamez commented on Source/Private/Validators/MapCheckValidator_Collisions.cpp
> +#include "Misc/UObjectToken.h"
Done.

2023-02-02 10:18 UTC, TheEmidee approved these changes

2023-02-02 10:18 UTC, merged